### ISSUE TITLE
Interviewing Collette Stahl-Francisco

### ISSUE THREAD

**Issue by collettesf** [planetoftheweb/fid#13]
## A link to your public class Github Repository

* https://github.com/collettesf/assignment1

## A link to your Github Pages site.

* https://collettesf.github.io/assignment1/

## What experience do you have building websites?

* The experience I have building websites is HTML/ CSS coding. I've been coding for 4 years at my previous place of employment. I first started my journey on a kids website www.neopets.com. Later I decided to explore my creativity and go school to enhance my coding skills.

## What software experience do you currently have?

* I have high advanced  software skills in Photoshop, InDesign, Illustrator, Lightroom and Word. In 2013 I went to school for Web Design to develop these skills. I am currently working on progressing my skills to learn more software.

## What are some of your strongest soft skills

* The best soft skills I have are Typing, Time Management and Effective Listening. I can type 60 words per minute with 99% accuracy rate. I schedule my entire day out the night before, to make sure I am using good time. When there is something important to remember I take notes and and ask questions.

## Where do you see yourself working after you complete your studies?

* I see myself working long term for your amazing company, you won't regret your decision. I've never been fired from any previous employment. I'm responsible and work hard towards any goal I need to achieve. If given the opportunity I wouldn't take it for granted one bit.

**Comment by planetoftheweb** [comment]
You were supposed to delete the defaults. All the stuff after "Before you ask a question, please look through through the issues to see if this question has been answered before."

**Comment by collettesf** [comment]
I have updated this. Did I do everything else correct?
