### ISSUE TITLE
YARE

### ISSUE THREAD

**Issue by yaretzi96** [planetoftheweb/fid#15]
**A link to your public class Github Repository:**
 https://github.com/yaretzi96/yare/
**A link to your Github Pages site:** 
https://yaretzi96.github.io/yare/ 
**A one or two sentence answer to each of the following questions (pretend you’re interviewing for a job in my company**
**What experience do you have building websites?**
I do not have any experience with building websites, but I am very interested with  the subject, I would like to understand the web designing world, and learn to integrate those things into my daily life and make use of them in the future.
**What software experience do you currently have?**
I have experience with the Adobe software, such as lightroom, photoshop, indesign and illustrator. Ive worked with those things on a daily for projects, and I've learned a lot of useful skills.
**What are some of your strongest soft skills (read this)?**
Some of my strong skills are illustration and any other art mediums with drawing, painting, photography and digital art as well. Although I started with digital art not too long ago, Im getting familiar with the tools very quickly and have learned a lot since. 
**Where do you see yourself working after you complete your studies?** 
After completing my studies I would like to pursue Graphic  Design or some kind of work that is dedicated to create.  I would like to focus on Illustration as well, its one of many interest that motivate me and definetly as a side business doing something with photography, or with an art medium.

**Comment by planetoftheweb** [comment]
A bit more formatting would be better, maybe you can work on it. Use Markdown.
