### ISSUE TITLE
Ozzy 

### ISSUE THREAD

**Issue by gamerOZZ911** [planetoftheweb/fid#16]
[**My Public class Github Repository**](https://github.com/gamerOZZ911/testrepo)

[**My Github Pages site**](https://gamerozz911.github.io/testrepo/)

1. **What experience do you have building websites?** 
The only experience I have when it comes to building websites was a high school class I took senior year called Web Design. This course instructed me on how to build a website using wix, creating an account, and building a template.

2. **What software experience do you currently have?** 
Due to past classes I have taken at Seminole State required for receiving my AA degree and transfer to UCF for my bachelors in Game Design, I am currently experienced in using adobe photoshop, illustrator, InDesign, AfterEffects, and Premiere Pro. I am also experienced in Microsoft Word, powerpoint, and office.

3. **What are some of your strongest soft skills?**
 My strongest soft skill I would say is Collaboration with others. This is mostly thanks to the numerous amount of projects I have worked on with other classmates back in college and high school.

4. **Where do you see yourself working after you complete your studies?** 
After I complete my studies, I see myself working in high end video game companies such as epic games and bethesda softworks studios after many years of game design experience. I most likely would see myself working my way up through smaller video game companies to start off and bouncing from them to the higher end companies like I already mentioned.

**Comment by planetoftheweb** [comment]
A bit more formatting would be better in these answers.
