### ISSUE TITLE
CRojas

### ISSUE THREAD

**Issue by CRojas5** [planetoftheweb/fid#17]
A link to your public class Github Repository
https://github.com/CRojas5/test1

A link to your Github Pages site.
https://crojas5.github.io/test1/

What experience do you have building websites?
 _I use to work at a digital marketing agency in downtown Orlando. While I was working there we would have some clients that came to us to build their website. I have no experience actually building the website, but I would talk with the Front End Web Designer at the agency about how it works because I thought it was interesting. I'm looking forward to learning more about it now and hope in the future to build my own small website._ 

What software experience do you currently have?
_The software I have the most experience in using would have to be Photoshop and some Illustrator. I'm no pro but I know enough at the moment to create some graphics and some gifs. I know how to use most Microsoft Word, PowerPoint, and Excel._ 

What are some of your strongest soft skills (read this)?
_Some of my strongest soft skills would be time management, collaboration, and communication. I would say time management is my strongest skill. When I worked in an agency, time management is key. There's a lot of clients, a lot of projects, and a lot to do._ 

Where do you see yourself working after you complete your studies?
_I graduated from UCF in 2016 with a B.A in Advertising and Public relations. I decided to come back to SSC and continue my studies and get two certificates. Afterwards I see myself working for a company that I'm passionate for such as soccer, make up, animals, or a non-profit. I also see myself doing some freelance work on the side focusing on helping small business improve their social presence._

**Comment by planetoftheweb** [comment]
The repository name shouldn't be REAMDE. That's the name of a file. I would create a different repository. Also, the link to your github pages site is not correct. Please take a peek at some of the other student's assignment as well as the documentation and try to fix it. Let me know if you don't understand something

**Comment by CRojas5** [comment]
I made the changes. Hope it's correct this time.
