### ISSUE TITLE
Marielle

### ISSUE THREAD

**Issue by mccox52** [planetoftheweb/fid#23]
1. Github Repository
https://mccox52.github.io/classrepository/
2. Github Pages
https://github.com/mccox52
3. What experience do you have building websites
I have no experience building websites except for with premade templates on Blogger or Wordpress. 
4. What software experience do you currently have?
I have basically no software experience except for Blogger and Wordpress. 
5. What are some of your strongest soft skills?
I believe problem solving and creative thinking are some of my strongest soft skills.  
6. Where do you see yourself working after you complete your studies?
I could see myself working for a graphic design company focusing on print.

**Comment by planetoftheweb** [comment]
The Github pages/Repository are reversed in order.
