### ISSUE TITLE
Kaitlyn Robinkoff

### ISSUE THREAD

**Issue by krobinkoff** [planetoftheweb/fid#8]
**A link to your public class Github Repository**
- [Github Repository](https://github.com/krobinkoff/testoftestoftest)

**A link to your Github Pages site.**
- [Github Page](https://krobinkoff.github.io/testoftestoftest/)

# **Questions**

### **What experience do you have building websites?**
_Though I had learned how to build websites back in middle school there is little that I remember from there. Otherwise I don't know anything except from those sites that have basically everything made for you or something similar to creating a blog via Google. Something which I have multiplies of as I had to make them back in school whenever it was required of me to when I had virtual classes._
 
### **What software experience do you currently have?**
_My main experience is in the Adobe Software Sweet with Photoshop being the main one. I have been using the Adobe Sweet since middle school, gaining the most experience and really going into it at the end of my Senior year of high school, where I was able to my certification for Photoshop, and moving into college I've gained more useful skills as well as refining the ones that I either taught myself or learned via tutorials involving the Adobe Sweet with the classes I have taken and am currently taking._

### **What are some of your strongest soft skills?**
_I can safe to say that I have good time  #management and data presentation as my strongest soft skills. My communication skills are useful too as they are needed to help connect with a team and to work together to get things done._

### **Where do you see yourself working after you complete your studies?**
_While I would see myself working in some type of company while trying to go freelance and try to get commissioned to get my name out and about for a little while. Though I want to see myself in an internship for a graphic design company sometime within the next year after i am done with my studies._

**Comment by planetoftheweb** [comment]
Hmm. I think that's one soft skill, the question was 'some' 'skills' plural, so you could add a few.

**Comment by krobinkoff** [comment]
It has been redone.
