### ISSUE TITLE
Danah

### ISSUE THREAD

**Issue by danahaldameth** [planetoftheweb/fid#9]
**A link to your public class Github Repository**

https://github.com/danahaldameth/danah

**A link to your Github Pages site.**

https://danahaldameth.github.io/danah/.

A one or two sentence answer to each of the following questions (pretend you’re interviewing for a job in my company)

**What experience do you have building websites?**
I have no experience at all with building websites besides sites such as wix where everything is kind of created for you and is predesigned. But no experience building raw data from the ground up. I have some experience with managing blogs but I'm not sure if that is creating websites because again everything is preordained. I also ran a Newspaper Club where we used Wordpress to digitally publish our issues so I am minimally comfortable with that type of website building. 

**What software experience do you currently have?**
I have experience with Photoshop, InDesign, Illustrator, and brief and minimal experience with Premiere Pro and After Effects. I am Certified in only Photoshop and InDesign. I'm also familiar with Microsoft programs such as Word, Powerpoint, and Publisher. As well as visually and mechanically familiar with social media softwares. 

**What are some of your strongest soft skills?**
My strongest skills can be being creative and trying to think outside the box. I also enjoy working brainstorming ideas with others. Another strong suit of mine is time management. I try to finish things consistently on time to make things easier for both parties. 

**Where do you see yourself working after you complete your studies?**
I see myself working in the Graphic Design field specifically into marketing and advertising and branding most of all. I'd like to be creating covers for books or movie posters or even a free lance branding designer for companies. I'm also not opposed to doing editorial page designs.

**Comment by planetoftheweb** [comment]
This could use a bit more formatting. Go ahead and try to make it better by editing it a bit with markdown.
